CREATE TABLE comments (
   id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   text text,
   user_id INTEGER NOT NULL,
   datetime TIMESTAMP,
   CONSTRAINT comments_pkey PRIMARY KEY (id)
);

ALTER TABLE comments ADD FOREIGN KEY (user_id) REFERENCES users(id);